### PR TITLE
Team-GP: announce and/or punish teammate hits

### PR DESCRIPTION
**Pull request by heuchi**
Here is my idea for making players more interested in avoiding teammate hits in team GPs. ;)

There are two options:

1. xml: "show-teammate-hits" (bool), lobby cmd: /admin hitmsg [0/1]
2. xml: "teammate-hit-mode" (bool) , lobby cmd: /admin teamhit [0/1]

If enabled, 1 will send messages about fatal hits to a teammate like this:
`LOL: <player1> just hit teammate <player2>`
There is a minimum delay of 1.5s between two messages to make sure, the message queue is not flooded.

If enabled, 2 will do the following:
If you hit a teammate you get an anvil. If you were shielded you only loose the shield (shield = gum bubble).
If you had a bomb attached you explode.
A hit is a any cake hit or a bowling ball that hasn't been fired more than 2s ago. It should be possible to avoid bowling balls that have been around for more than 2s?

If you swatter a teammate you loose the swatter immediately.
If this is the first kart you swatter in the first 3s you have the swatter you also get an anvil.
The anvil will be less severe, if you only deshielded your teammate.

I have done some testing with several players (among them mimiz, frenchi, nimeye and Anneke). They all said they find it interesting. The server never crashed and to me it seems like it's working as expected. It's not easy to be sure, because there are some corner cases. One being, that a cake explosion doesn't need to exactly hit the kart. If a cake hits the ground close enough to a kart, the kart still explodes. This is done in ExplosionAnimation::create(). Kind of a strange place actually, which took me some time to figure out...

Anyway, I think the system's ready for a real-life test, which I cannot really do. But since you haven't seen it yet, I'll be happy to set up my server, so you won't need to compile just to see it working. Just send me a pm.

## Agreement
```
By creating a pull request in stk-code, you hereby agree to dual-license your contribution as
GNU General Public License version 3 or any later version and
Mozilla Public License version 2 or any later version.

This includes your previous contribution(s) under the same name of contributor.

Keep the above statement in the pull request comment for agreement.

```

### CODE REVIEW

**Comment by heuchi** [comment]
There's a [video from TheZilag on YouTube](https://www.youtube.com/watch?v=SBG60acImYc) of a test team gp we did on July 4th.

Do you know why it doesn't pass the "switch" test? To me it looks like there's a library missing for ld. But I don't understand how my code could have caused that.

**Comment by kimden** [comment]
I don't understand either why switch build fails, apparently it can happen even after changing a single server_lobby.cpp (a647e07)...

**Comment by heuchi** [comment]
Finally I have some time again and tried to refactor this:
I've moved most of it to ServerLobby. Let me know what you think of it.
I have only done some simple testing yet. But it seems to work.

There's one thing I was wondering:
As far as I understand <i>m_team_for_player</i> has the information in what team a player is. But this is indexed by the player's name (std::string), which makes it a bit complicated to access, because I'm using a string conversion every time, I want to check if two players are in the same team. I currently use the player ID (<i>m_teammate_current_item_ownerID</i> for the owner for example) to identify them, so it works like this:
<pre>
// get team of owner of item

const std::string ownername =
    StringUtils::wideToUtf8(RaceManager::get()->getKartInfo(m_teammate_current_item_ownerID).getPlayerName());
const int ownerTeam = m_team_for_player[ownername];
</pre>
Is there an easier way? Although it seems the server (having no graphics) doesn't have performance problems.

**Comment by heuchi** [comment]
Added string option <i>teammate-hit-msg-prefix</i> to set the prefix for teammate hit messages (default is "LOL: ")
Can be set in server config file like this:
<pre>
    &lt;!-- Set string prefix for teammate hit messages.
         (Make sure it ends with a whitespace if non-empty.) --&gt;
    &lt;teammate-hit-msg-prefix value="Team-GP: " /&gt;
</pre>

**Pull request merged**
